// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzllgvbyuxkzlxgtaxhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56bGxndmJ5dXhremx4Z3RheGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDUwNTAsImV4cCI6MjA2ODY4MTA1MH0.SpyHa39L6Yuh45tqPNmkLGLLgjDtr4c4ZFFvUFpYAd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});